apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    name: website
spec:
  containers:
    - name: website
      image: sudipdas2001/website
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
